import { Prisma } from "@prisma/client";
import { prisma } from "./prisma";
import { makeId } from "./utils";
import type { TripDTO } from "@/types";

/**
 * Write a client-side trip (one built as a guest) into Postgres under a real
 * owner. Ids are regenerated by the database, so the maps from old to new ids
 * are kept while writing in order to preserve the activity→voucher links that
 * make the locker useful.
 */
export async function persistTripDTO(trip: TripDTO, ownerId: string, ownerEmail: string, ownerName: string) {
  const created = await prisma.trip.create({
    data: {
      title: trip.title,
      destinationId: trip.destinationId ?? undefined,
      destinationName: trip.destinationName,
      country: trip.country,
      latitude: trip.latitude,
      longitude: trip.longitude,
      startDate: new Date(trip.startDate),
      endDate: new Date(trip.endDate),
      coverImage: trip.coverImage,
      travelStyle: trip.travelStyle,
      totalBudget: new Prisma.Decimal(trip.totalBudget ?? 0),
      currency: trip.currency,
      visibility: trip.visibility ?? "PRIVATE",
      ownerId,
    },
  });

  const activityIdMap = new Map<string, string>();
  for (const a of trip.activities) {
    const row = await prisma.itineraryActivity.create({
      data: {
        tripId: created.id,
        dayNumber: a.dayNumber,
        startTime: a.startTime,
        endTime: a.endTime,
        category: a.category,
        name: a.name,
        locationName: a.locationName,
        address: a.address,
        latitude: a.latitude,
        longitude: a.longitude,
        cost: new Prisma.Decimal(a.cost ?? 0),
        currency: a.currency,
        notes: a.notes,
        bookingStatus: a.bookingStatus,
        sortOrder: a.sortOrder,
      },
    });
    activityIdMap.set(a.id, row.id);
  }

  for (const d of trip.documents) {
    await prisma.documentVoucher.create({
      data: {
        tripId: created.id,
        activityId: d.activityId ? activityIdMap.get(d.activityId) ?? null : null,
        category: d.category,
        title: d.title,
        provider: d.provider,
        confirmationCode: d.confirmationCode,
        fileUrl: d.fileUrl,
        fileName: d.fileName,
        fileSize: d.fileSize,
        startDate: d.startDate ? new Date(d.startDate) : null,
        endDate: d.endDate ? new Date(d.endDate) : null,
        details: d.details,
        cost: new Prisma.Decimal(d.cost ?? 0),
        currency: d.currency,
        cancellationDeadline: d.cancellationDeadline ? new Date(d.cancellationDeadline) : null,
        notes: d.notes,
      },
    });
  }

  for (const e of trip.expenses) {
    const row = await prisma.expense.create({
      data: {
        tripId: created.id,
        activityId: e.activityId ? activityIdMap.get(e.activityId) ?? null : null,
        title: e.title,
        amount: new Prisma.Decimal(e.amount ?? 0),
        currency: e.currency,
        category: e.category,
        date: new Date(e.date),
        // A guest has no user record, so the payer is matched by name.
        paidById: e.paidByName === ownerName ? ownerId : null,
        paidByName: e.paidByName,
      },
    });
    for (const s of e.splits) {
      await prisma.expenseSplit.create({
        data: {
          expenseId: row.id,
          userId: s.participantName === ownerName ? ownerId : null,
          participantName: s.participantName,
          splitAmount: new Prisma.Decimal(s.splitAmount ?? 0),
          isSettled: s.isSettled,
        },
      });
    }
  }

  if (trip.packingItems.length > 0) {
    await prisma.packingItem.createMany({
      data: trip.packingItems.map((p, i) => ({
        tripId: created.id,
        category: p.category,
        title: p.title,
        isPacked: p.isPacked,
        isEssential: p.isEssential,
        sortOrder: p.sortOrder ?? i,
      })),
    });
  }

  // The new owner always gets an accepted OWNER row; guest-era invitees stay pending.
  await prisma.tripCollaborator.create({
    data: {
      tripId: created.id,
      userId: ownerId,
      email: ownerEmail,
      role: "OWNER",
      inviteToken: makeId("tok"),
      status: "ACCEPTED",
    },
  });

  for (const c of trip.collaborators) {
    if (c.email.toLowerCase() === ownerEmail.toLowerCase()) continue;
    const existingUser = await prisma.user.findUnique({ where: { email: c.email.toLowerCase() } });
    await prisma.tripCollaborator.create({
      data: {
        tripId: created.id,
        userId: existingUser?.id ?? null,
        email: c.email.toLowerCase(),
        role: c.role === "OWNER" ? "EDITOR" : c.role,
        inviteToken: makeId("tok"),
        status: "PENDING",
      },
    });
  }

  return created.id;
}
